services:
  jirametrics:
    image: flow-metrics-jirametrics
    container_name: flow-metrics-jirametrics
    build:
      context: .
      args:
        INSTALL_PRE: ${INSTALL_PRE:-false}
        SUPERCRONIC_VERSION: ${SUPERCRONIC_VERSION:-v0.2.44}
    environment:
      CRON_SCHEDULE: ${CRON_SCHEDULE:-*/5 * * * *}
      INSTALL_PRE: ${INSTALL_PRE:-false}
      PORT: ${PORT:-8000}
      TZ: Europe/Vienna
    volumes:
      - ./myreports:/config
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
